// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAdlYXheG_ayULkNoWqcAH9bO2lOuAu4I',
    appId: '1:412629149442:android:09a66a157a6b4d18e0c41b',
    messagingSenderId: '412629149442',
    projectId: 'chatapp-181d7',
    storageBucket: 'chatapp-181d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4yDJNiG-WvU9xMtsBzuOEwJm1RZnXaU0',
    appId: '1:412629149442:ios:9695734f8098f43ee0c41b',
    messagingSenderId: '412629149442',
    projectId: 'chatapp-181d7',
    storageBucket: 'chatapp-181d7.appspot.com',
    androidClientId: '412629149442-supsjf7e703o2i81bpg4a9sjoeftadiu.apps.googleusercontent.com',
    iosClientId: '412629149442-vi697umn82f4darer52am2mqcusb1sg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
